### ISSUE TITLE
Gallery order wrong

### ISSUE THREAD

**Issue by greatknave** [enviragallery/envira-gallery-lite#27]
Helpscout Ticket: https://secure.helpscout.net/conversation/1145876324/72060?folderId=3302565

## Debug Information (From System Info Tab)
<details>
<summary>System Info Data</summary>
n/a
</details>

## Expected Behavior

The order the images are in on the back-end of the site should be the order they're in on the front-end of the site.

## Current Behavior

The order in the front-end doesn't match the order in the back-end. There doesn't seem to be a rhyme or reason for the order it's in on the front-end. It isn't changing randomly or anything; it's very much solidly set, and if you rearrange the order in the back-end, the front-end changes — just not in the way you'd want.

## Possible Solution

Not seeing anything in the console.

## Steps to Reproduce (for bugs)

1. Go to [this gallery](https://in-dental.com/patrocinadores/).
2. Check the order out.
3. Now go to the gallery in the back-end, [right here](https://in-dental.com/wp-admin/post.php?post=2386&action=edit).
4. Compare the order you see there to the order you see in the front.

Tested naked to no avail. Also can't repo this on local or testing. Made my own gallery on his site, though, and the problem shows up in my test gallery there.
 
## WP-ADMIN Access And Url

https://www.in-dental.com/wp-login.php
diana
1389858

## FTP Info

```
ftp.in-dental.com
Port 21
User: u836616488.Envira
Pass: Envira12345
```

## Your Environment

Browser name and version:
Operating System and version (desktop or mobile):

**Comment by dimensionmedia** [comment]
With Envira or Envira Lite whenever there is a column format that doesn't seem to match the order on the frontend vs. backend, it's probably because the isotope is trying to auto sort them and images that looks like they are exactly the same size aren't. therefore you might have to turn on cropping in "config" tab (exists for both pro and Lite). 

@greatknave closing this trusting you'll reach out to customer.
