### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by akyusa01** [enviragallery/envira-gallery-lite#3]
Moved from https://github.com/enviragallery/envira-gallery-plugin/issues/1617

> I think its time we add a proper welcome screen to Envira Gallery and Lite. Lets make this happen for FB3

**Comment by akyusa01** [comment]
Leaving open

**Comment by dimensionmedia** [comment]
@nathansingh1 this is on lite.enviragallery.com

![Screenshot 2019-06-03 10 29 48](https://user-images.githubusercontent.com/721134/58809777-8c0cc780-85ea-11e9-9c41-08d29a07b139.png)

**Comment by nathansingh1** [comment]
@dimensionmedia  I combed through Lite, here are comments for both the Welcome Screen and the rest of the plugin's tabs.

### Welcome Screen Specific comments:
1. From the What's New tab - assuming we don't have a graphic for this yet? If not, any idea where these came from?
https://cl.ly/14b1ee1d6316

2. From the Update Envira Gallery tab - -Grammar issue
https://cl.ly/e283eeda954e

3. From the Update Envira Gallery tab - Integration spelled incorrectly
https://cl.ly/fadadddd8648

4. From the "Upgrade Envira Gallery" Tab - Missing "I" on Instantly 
https://cl.ly/1b30197ca795

5. Possible to have the Addons page open within the tab like the others? 
https://cl.ly/aac8bd6fd029

### General comments for Lite Marketing verbiage:

6. I suggest we make these just "Galleries" for simplicity and accuracy to describe whats inside.
https://cl.ly/f58b7644da3a

7. -Update marketing text https://cl.ly/cae4f7350771. Leave the hyperlinks as is.
-Lets also put 3 of the features below on the left and the other 2 on the right.
-I just noticed GH turned all my "+"s into bullets. Please apply this to the rest of these below for this list. They should look like this https://cl.ly/ff86e5b27612. A plus sign with a double space before each feature "+  ". 

"By upgrading to Envira Pro, you can get access to numerous other features, including: 

+  Albums
+  Gallery Themes/Layouts, 
+  Image Proofing 
+  eCommerce
+  Dedicated customer support and so much more!

**Bonus:** Envira Lite users get a discount code for 20% off regular price."

8. -Lets update the format of this msg https://cl.ly/e65ee0dd4bc6 to the one below.
-Lets put 3 of the features below on the left and the other 2 on the right for balance.
-Lets put that picture of 5 stars below in parenthesis similar to this https://cl.ly/b148de6a0b2a

"By upgrading to Envira Gallery Pro, you can get access to numerous other gallery display features, including: 

We know that you will truly love Envira Gallery Pro. It has 1000 five star ratings https://cl.ly/bd77db1972ac and is active on over 150,000 websites.

+  [Custom image tagging and filtering](https://enviragallery.com/addons/tags-addon/)
+  [Mobile specific image assets for blazing fast load times](https://enviragallery.com/features/responsive-mobile-friendly/)
+  [Dedicated and unique gallery URLs](https://enviragallery.com/addons/deeplinking-addon/)
+  [Custom gallery themes](https://enviragallery.com/demo/envira-gallery-theme-demo/)
+  Gallery thumbnail support and so much more!

**Bonus:** Envira Lite users get a discount code for 20% off regular price."

9. -Lets update the format of this Lightbox marketing msg.
-Lets put 4 of the features from below on the left and the other 4 on the right for balance.
https://cl.ly/0aee87602f8c

"By upgrading to Envira Gallery Pro, you can get access to numerous other Lightbox features, including: 

+  [Custom Lightbox titles](https://enviragallery.com/demo/lightbox-gallery-demo/)
+  [Enable/disable Lightbox controls (arrow, keyboard and mouse wheel navigation)](https://enviragallery.com/demo/lightbox-gallery-demo/#!enviragallery381249-497120)
+  [Custom Lightbox transition effects](https://enviragallery.com/demo/lightbox-transitions-demo/)
+  [Native fullscreen support](https://enviragallery.com/demo/fullscreen-demo/)
+  [Gallery deeplinking](https://enviragallery.com/demo/deeplinking-demo/)
+  [Image protection](https://enviragallery.com/demo/password-protection-addon/)
+  [Lightbox supersize effects](https://enviragallery.com/demo/lightbox-gallery-demo/)
+  [Lightbox slideshows](https://enviragallery.com/demo/lightbox-gallery-demo/) and so much more!

**Bonus:** Envira Lite users get a discount code for 20% off regular price."

10. -Graphic missing here https://cl.ly/3a5ab2209e8d for Mobile tab, looks like it was there before.
-Update link for mobile demo button -> https://enviragallery.com/features/responsive-mobile-friendly/

11. -Update the Mobile tab text here https://cl.ly/3a5ab2209e8d

Build responsive WordPress galleries that work on mobile, tablet and desktop devices. You can even customize various aspects of your user's mobile gallery display experience to be different than desktop.

**Bonus:** Envira Lite users get a discount code for 20% off regular price."

12. -Update View Video Addon Demo button, graphic and video links here
https://cl.ly/94ea13000eb9
all to https://enviragallery.com/demo/video-gallery-demo/
-Lets use "+" instead of the bullets for the video links

14. -Add the following  text at the bottom above the buttons "**Bonus:** Envira Lite users get a discount code for 20% off regular price."

15. -Update Social Addon Demo button, social links and graphic here
https://cl.ly/0b2e92c24a50
all to https://enviragallery.com/demo/social-sharing-demo/
-Lets use "+" instead of the bullets for the social links
-Add the following  text at the bottom above the buttons "**Bonus:** Envira Lite users get a discount code for 20% off regular price."

16. -Update Tags button and graphic:
https://cl.ly/44a388df372c

-Update tags marketing text to: 
"By upgrading to Envira Gallery Pro, you can add Tags to your gallery images (and categories to Albums). Allow users to filter your galleries by tag and so much more!

**Bonus:** Envira Lite users get a discount code for 20% off regular price."

17. -Update the Pagination text here https://cl.ly/8239f72e33aa to:

"If you have a lot of photos in your gallery, you can split your Gallery across multiple pages! Customize a variety of aspects including how many items are shown per page, button text, left/right arrows, and more. 

Available pagination options include:"

-Lets use "+" instead of the bullets

-Add the following  text at the bottom above the buttons "Bonus: Envira Lite users get a discount code for 20% off regular price."

18. -Update Social Addon Demo button, social links and graphic link here
https://cl.ly/d0c6edacad9e to https://enviragallery.com/demo/gallery-pagination-demo/

19. -Update the text in the Misc tab here https://cl.ly/bb073e70eb6f to:

"By upgrading to Envira Gallery Pro, you can get access to numerous other features, including:

+  [Fully-integrated import/export module for your galleries](https://enviragallery.com/features/)
+  [Custom CSS controls](https://enviragallery.com/addons/css-addon/) for each gallery and so much more!

**Bonus:** Envira Lite users get a discount code for 20% off regular price."

**Comment by dimensionmedia** [comment]
went ahead and updated addons tab, will push to test server shortly.

![Screenshot 2019-06-12 16 09 07](https://user-images.githubusercontent.com/721134/59382769-74d98280-8d2c-11e9-9786-af16cbfab85e.png)

**Comment by nathansingh1** [comment]
@dimensionmedia findings from my review. I'm still working on what I want to do for the Lite vs Pro and About Us tabs.

-This should be Envira Gallery.
https://cl.ly/bbe6134a1f71
Its my understanding that this may be a WP related limitation (name of the plugin and the first item on the menu) if so let me know.

-Lets update this to All Galleries
https://cl.ly/b222140e7677

-We don't need the "Upgrade Envira Gallery" in the left menu
https://cl.ly/2e5ec40ba84c 

-Lets Add an "About Us" here that goes to the About Us tab. Leave the font color the same as "Add New" 
https://cl.ly/fb87554877ed

-Looks like something happened to the tab layout vs last time 
https://cl.ly/62c6967187f1

-Update the button wording here
https://cl.ly/521502c4de06

-Remove Support option from right panel 
https://cl.ly/7e0ce9745ad6

-Add a double space before each feature "+  ". Apply this to all of the areas we use +. They should look like this https://cl.ly/ff86e5b27612. 

-Your probably aware, but several items from the last set of issues I sent are still open.

-The heading here https://cl.ly/4aa082c1dc7f should be: "Want to do even more with your gallery display?"
https://cl.ly/3c5f005603a9

-The description wording here https://cl.ly/4aa082c1dc7f should be like this:

"We know that you will truly love Envira Gallery Pro. It has 1000 five star ratings (*****) and is active on over 150,000 websites.

By upgrading to Envira Gallery Pro, you can get access to numerous other gallery display features, including:"

-The stars above need to look like this https://cl.ly/adb8a381dc67
You can possiblly take them from WPForms here http://lite.enviragallery.com/wp-admin/admin.php?page=wpforms-settings

-Indent so the text is aligned 
https://cl.ly/77e7b8a6f1c8
https://cl.ly/b5e983c78f21
https://cl.ly/fbbe7ba5fcd1
https://cl.ly/fbbe7ba5fcd1

-Link the graphic to the demo button link for Mobile, Videos, Social, Tags and Pagination tabs respectively.

-Update this to "Stay in Touch!" instead of Newsletter Signup 
https://cl.ly/adb3695845c2

-Increase the size of this button https://cl.ly/3d4a7cb752d0 to a larger size maybe near the one we have on our homepage https://cl.ly/ae44c9c67817

-Change log should only be 1-4 versions back
http://lite.enviragallery.com/wp-admin/edit.php?post_type=envira&page=envira-gallery-lite-changelog

-Can we increase the whitespace between the tabs?
https://cl.ly/3c31bc0e2af7

-Looks like the Title text disappeared from all the Addons when they were brought into the tab
https://cl.ly/854120ba73d6

-Update these to font-size: 18px; margin: 30px 0; 
Currently, its using the 13px default styling from WP which is too small.
https://cl.ly/2add375c5b49

-Lets have these headings be the same size/style 
https://cl.ly/d260028b0f6e
https://cl.ly/d19d53909be1

**Comment by nathansingh1** [comment]
Comments from our talk today:

-Remove Addons tab (side note: this may be something we add back later in a future revision)

-Looks like the buttons got larger here for all the areas? https://cl.ly/6a9f5bdd6ed3
For the comment below, I was referring only to this area https://cl.ly/4a244ccbe069 (should have taken a larger screenshot of that earlier)
"Increase the size of this button https://cl.ly/3d4a7cb752d0 to a larger size maybe near the one we have on our homepage https://cl.ly/ae44c9c67817"

-Lets make this "It has 1,000+ five star..." https://cl.ly/cb0e95b26daa

-Looks like the "+  " went missing in some areas? https://cl.ly/3ed012ede64b

-FAQ & Support - this tab needs to be removed and we'll revisit for a future revision

-Envira Gallery block graphic missing still https://cl.ly/14b1ee1d6316

-Get rid of Change log tab, and add past and current version info on the Whats New tab per our discussion.

-Remove Helpful Articles For Beginners from Whats New tab, but keep it in the Get Started

-Remove Support link here: https://cl.ly/ae6483a373ee

-Add social icons instead of text (similar to our website): https://cl.ly/b5cc89cf850e for both Whats New and Get Started. 
Also, add Pinterest icon and link: https://www.pinterest.com/enviragallery/

-Lets remove this verbiage: "and tell us what you would to see in future updates." https://cl.ly/f87745a7ba93

**Comment by nathansingh1** [comment]
Please change this button size back to what it was https://cl.ly/9e19de50bd39

Other then that this 1st iteration looks good to go

**Comment by dimensionmedia** [comment]
done. this is on lite.enviragallery.com but assuming we are good with this for the next release! :-)

**Comment by dimensionmedia** [comment]
Closing this - welcome screen has been out a while. New tickets can address updates. cc: @nathansingh1 @chrisakelley
